name: Build NDS File
on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: devkitpro/devkitarm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build NDS
        run: make

      - name: Upload NDS
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            DSpTracker.nds
            trackersave.bin
            DSpTrackerManual.pdf
        
